### ISSUE TITLE
Setting font to false gives an error (in the demo)

### ISSUE THREAD

**Issue by Skaruts** [Crutiatix/TICuare#2]
Hi, I was playing around with the demo I downloaded from your itch.io page, and when I set `font` to false (in any element) it gives me an error: 
`12: attempt to perform arithmetic on a nil value (local 'm')`

The demo uses the min version (on line 12), so I replaced it with the normal version and it gives me this error:
`410: attempt to perform arithmetic on a nil value (local 'text_width')`

**Comment by Skaruts** [comment]
I changed 
```
function ticuare.print(...)
    -- (...)
    if color then
        local width, height = print(...    --<-- width is initialized inside the 'if'
    end
    return width, height
end
```
to
```
function ticuare.print(...)
    -- (...)
    local width                            --<-- I moved it here
    if color then
        width, height = print(...
    end
    return width, height
end
```
and it doesn't give me that error anymore. It shows the text black, but I realize I need to change the colors from three tables to one.

However, I don't quite understand the min version of it.

```
function ticuare.print(t,i,a,o,n,e)
	n=n or false 
	e=e or 1 local                     -- doesn't this 'e' conflict with the ones below
	d,r=t:gsub("\n","")
	if o then 
		local e,e=print(t,i,a,o,n,e),(6+r)*e*(r+1)      -- two 'e's?
	end 
	return width,height                -- width, height or 'e'?
end
```
But it seems to work if I change it to:
```
    local w,h
    if o then 
        w,h=print(t,i,a,o,n,e),(6+r)*e*(r+1)
    end 
    return w,h 
```

**Comment by Crutiatix** [comment]
@Skaruts Sorry for the late respond. I don't understand how is my snippet at itch.io for rendering fonts related to this issue. However there is bug in TICuare as you described it and I fixed it. Thank you 😊 
Also added exception when text.font == false and text.colors is array of arrays of numbers. Hope It helps to avoid problems with colors of text when switching between font and non-font print.

**Comment by Skaruts** [comment]
Hey, my turn to say sorry for the late response, and thanks. I had no more problems since I made that fix, but in future projects I'll use the newest version. 

Just in case you're interested, I've made a UI with it [in this game](https://tic.computer/play?cart=753) (I shortened it a bit more, renamed 'ticuare' to 'tc', I hope that's ok -- I was going over the char limit). I had made most of this back when I opened this issue, but only now I came back to it and finished it.

Actually love this UI lib. Thanks.

**Comment by Skaruts** [comment]
@Crutiatix hello again, I have no issues, I just would like to ask you a question:

Is there some way to set a button to react to other mouse buttons? 

I can't find this in the documentation. I'd like to make a button that can be activated by both left-click or right-click.
